# Generated by Django 3.0.8 on 2020-09-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200924_2146'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='favorites',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
