# Generated by Django 3.1.1 on 2020-09-26 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200924_2146'),
        ('authentication', '0002_appuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='following',
            field=models.ManyToManyField(related_name='_appuser_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
