# Generated by Django 3.1.1 on 2020-10-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200926_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='picture',
            field=models.URLField(default='https://static.productionready.io/images/smiley-cyrus.jpg'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
