# Generated by Django 3.1.1 on 2020-10-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201002_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='picture',
            field=models.URLField(default='https://static.productionready.io/images/smiley-cyrus.jpg', max_length=2000),
        ),
    ]
